import 'package:freezed_annotation/freezed_annotation.dart';

part 'task.freezed.dart';

/// Domain entity representing a task in the application.
/// This is the core business object that represents a task with its properties.
@freezed
class Task with _$Task {
  const factory Task({
    required String id,
    required String title,
    required String description,
    required bool isCompleted,
    required DateTime createdAt,
    required DateTime updatedAt,
  }) = _Task;

  const Task._();

  /// Creates a new task with default values.
  factory Task.create({
    required String title,
    required String description,
  }) {
    final now = DateTime.now();
    return Task(
      id: '', // Will be generated by repository
      title: title,
      description: description,
      isCompleted: false,
      createdAt: now,
      updatedAt: now,
    );
  }

  /// Creates a copy of the task with updated completion status.
  Task toggleCompletion() {
    return copyWith(
      isCompleted: !isCompleted,
      updatedAt: DateTime.now(),
    );
  }

  /// Creates a copy of the task with updated title and description.
  Task updateContent({
    required String title,
    required String description,
  }) {
    return copyWith(
      title: title,
      description: description,
      updatedAt: DateTime.now(),
    );
  }
}

